# Generated by Django 6.0.2 on 2026-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='payroll',
        ),
    ]
