# Generated by Django 6.0.2 on 2026-02-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payroll',
            table='payroll',
        ),
    ]
